config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: %i[index new show create] do
    resources :bookings, only: %i[create show new update]
  end
  resources :bookings, only: %i[]  do
    resources :reviews, only: %i[new create]
  end
  # get '/bookings/:booking_id/reviews/new', to: 'reviews#new', as: 'new_review'
  # post '/bookings/:booking_id/reviews/create', to: 'reviews#create'
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :reviews, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true
  STATUS = ["pending", "confirmed", "declined"]
  validates :status, inclusion: { in: STATUS }
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many_attached :picture_url
  CATEGORY = ["kitesurf", "paddle", "planche à voile", "planche de surf", "vélo", "roller", "ski", "snowboard", "skateboard", "raquette de tennis"]
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 1}
  validates :location, presence: true
  validates :sport_category, presence: true, inclusion: { in: CATEGORY, message: "Please select existing sport category"}
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: 0..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers, dependent: :destroy
  has_many :bookings
  has_many :reviews
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(
      start_date: params[:start_date],
      end_date: params[:end_date],
      offer: @offer,
      user: current_user
    )
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    @offer = Offer.find(@booking.offer_id)
    @booking.user = current_user
    authorize @booking
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new
    @booking.start_date = params[:start_date]
    @booking.end_date = params[:end_date]
    @booking.offer = @offer
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboard_path(@offer, @booking)
    else
      render 'offers/show', status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = params[:booking][:status]
    @booking.save
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    if params[:sport_category].present?
      @offers = Offer.where("title ILIKE '%#{params[:sport_category]}%'")
    elsif params[:query].present?
      sql_query = "title ILIKE :query OR location ILIKE :query"
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @booking = Booking.new
    @markers = [{lat: @offer.latitude, lng: @offer.longitude}]
    authorize @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :price, :location, :sport_category, picture_url: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  # add other pages to "only" list

  def home
    @offers = Offer.last(3)
  end

  def dashboard
    @my_offers = Offer.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    @review.user = current_user
    authorize @review
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to dashboard_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container pt-5">
  <div class="mb-5 pt-5">
  <br>
    <h2><%= link_to "<    Demande de réservation", offer_path(@offer), class:"text-decoration-none" %></h2>
  </div>

  <div class="d-flex justify-content-between">

    <div class="dates_et_confirmation" style="width: 600px">
      <div class="d-flex justify-content-between border-bottom border-top border-secondary pb-4">
        <div class="flex-fill mt-3">
          <h4>Votre réservation</h4>
          <div class="d-flex justify-content-between mt-3">
            <div>
              <h5>Dates</h5>
              <p><%= @booking.start_date %> - <%= @booking.end_date %> </p>
            </div>
            <h5><%= link_to "Modifier", offer_path(@offer) %></h5>
          </div>
        </div>

      </div>

      <div class="mt-3">
        <p class="btn btn-success mt-3"><%= link_to "Confirmer la demande", offer_bookings_path(@offer, start_date: params[:start_date], end_date: params[:end_date]), data: {turbo_method: :post},class:"text-decoration-none bl" %></p>
      </div>

    </div>

    <div class="border" style="border-radius: 5px">

      <div class="d-flex justify-content-start pb-2 m-4">
        <div style="width: 150px">
            <%= @offer.picture_seed ? (image_tag(@offer.picture_seed.split(",").first, style: "width: 150px")) : (cl_image_tag(@offer.picture_url.first.key, style: "width: 150px")) %>
        </div>
        <div class="container" style="margin: auto">
          <h5><%= @offer.title %></h5>
          <h6><%= @offer.location %></h6>
        </div>
      </div>

      <div class="border-bottom border-top border-secondary py-2 m-4">
        <h4>Détails du prix</h4>
        <div class="d-flex justify-content-between">
          <% length = (@booking.end_date - @booking.start_date).to_i %>
          <% total = length * @offer.price %>
          <div><%= @offer.price %> x <%=length %> jours</div>
          <div><%= total %> €</div>
        </div>
      </div>

      <div class="d-flex justify-content-between pt-2 price_total m-4">
        <div>Total</div>
        <div><%= total %> €</div>
      </div>

    </div>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="container p-5">
  <br>
  <br>
  <br>
  <div class="mb-5">
    <h2><%= link_to "<    Demande de réservation", offer_path(@offer), class:"text-decoration-none" %></h2>
  </div>

  <div class="d-flex justify-content-between">

    <div class="dates_et_confirmation" style="width: 600px">
      <div class="d-flex justify-content-between border-bottom border-top border-secondary pb-4">
        <div class="flex-fill mt-3">
          <h4>Votre réservation</h4>
          <div class="d-flex justify-content-between mt-3">
            <div>
              <h5>Dates</h5>
              <p><%= @booking.start_date %> - <%= @booking.end_date %> </p>
            </div>
            <h5><%= link_to "Modifier", offer_path(@offer) %></h5>
          </div>
        </div>

      </div>

      <div class="mt-3">
        <p class="btn btn-success mt-3"><%= link_to "Confirmer la réservation", offers_path, class:"text-decoration-none bl" %></p>
      </div>
    </div>

    <div class="border" style="border-radius: 5px">

      <div class="d-flex justify-content-start pb-2 m-4">
        <div style="width: 150px">
            <%= offer.picture_seed ? image_tag(offer.picture_seed.split(",").first) : cl_image_tag(offer.picture_url.first.key), style:"width: 150px" %>
        </div>
        <div class="container" style="margin: auto">
          <h5><%= @offer.title %></h5>
          <h6><%= @offer.location %></h6>
        </div>
      </div>

      <div class="border-bottom border-top border-secondary py-2 m-4">
        <h4>Détails du prix</h4>
        <div class="d-flex justify-content-between">
          <% length = (@booking.end_date - @booking.start_date).to_i %>
          <% total = length * @offer.price %>
          <div><%= @offer.price %> x <%=length %> jours</div>
          <div><%= total %> €</div>
        </div>
      </div>
      <div class="d-flex justify-content-between pt-2 price_total m-4">
        <div>Total</div>
        <div><%= total %> €</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GEARSports</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('gear-sport-favicon.png') %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <%= yield %>
    <br>
    <br>
    <%= render "shared/footer" %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/offers/index.html.erb
<div class="container mt-5 pt-5 pb-5">
  <div class="icon-nav mt-4 mb-5 d-flex justify-content-between">
    <div class="d-flex align-items-start flex-column link">
        <%= link_to offers_path(sport_category: "snowboard"), class:"text-decoration-none text-center link active" do %>
          <i class="fa-solid fa-person-snowboarding mb-2"></i>
          <p>Snowboard</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "voile"), class:"text-decoration-none text-center link" do %>
          <i class="fa-sharp fa-solid fa-sailboat mb-2"></i>
          <p>Voile</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "paddle"), class:"text-decoration-none text-center link" do %>
          <i class="lni lni-surf-board mb-2"></i>
          <p>Paddle</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "kite"), class:"text-decoration-none text-center link" do %>
          <span class="material-symbols-outlined">
            kitesurfing
          </span>
          <p>Kitesurf</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "Vélo"), class:"text-decoration-none text-center link" do %>
          <i class="fa-sharp fa-solid fa-bicycle mb-2"></i>
          <p>Vélo</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "skate"), class:"text-decoration-none text-center link" do %>
          <span class="material-symbols-outlined">
            skateboarding
          </span>
          <p>Skateboard</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "ski"), class:"text-decoration-none text-center link" do %>
          <i class="fa-solid fa-person-skiing mb-2"></i>
          <p>Ski</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "roller"), class:"text-decoration-none text-center link" do %>
          <span class="material-symbols-outlined">
            roller_skating
          </span>
          <p>Roller</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "tennis"), class:"text-decoration-none text-center link" do %>
          <span class="material-symbols-outlined">
            sports_tennis
          </span>
          <p>Tennis</p>
        <% end %>
    </div>
    <div class="d-flex align-items-start flex-column">
        <%= link_to offers_path(sport_category: "planche de surf"), class:"text-decoration-none text-center link" do %>
          <span class="material-symbols-outlined">
            surfing
          </span>
          <p>Surf</p>
        <% end %>
    </div>
  </div>
  <div class="cards">
    <% @offers.each do |offer| %>
      <div class="card-offer-with-heart">
        <a href=""><i class="far fa-heart card-heart"></i></a>
        <%= link_to offer_path(offer), class:"text-decoration-none" do %>
          <div class="card-offer">
              <%= offer.picture_seed ? image_tag(offer.picture_seed.split(",").first) : cl_image_tag(offer.picture_url.first.key) %>
              <div class="card-offer-infos">
                <div>
                  <div class="d-flex justify-content-between">
                    <h2><%= offer.title %></h2>
                    <% sum = 0 %>
                      <%offer.reviews.each do |review|%>
                          <% sum += review.rating %>
                        <% end %>
                      <h4><%= (offer.reviews.count == 0) ? "" : (sum.fdiv(offer.reviews.count)).round(1) %>   <span class="fa-solid fa-star text-warning"> </h4>
                  </div>
                  <h3><%= offer.location %></h3>
                  <h4 class="card-offer-pricing"><%= offer.price %> € / day</h4>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/offers/new.html.erb
<div class="container">
  <div class="offer">
    <h1>Make an offer</h1>
    <%= simple_form_for (@offer) do |f| %>
      <%= f.input :title, placeholder: "What do you rent?" %>
      <%= f.input :description, placeholder: "Tell us more" %>
      <%= f.input :price, placeholder: "What's your daily price?" %>
      <%= f.input :location, placeholder: "What's your address?" %>
      <%= f.input :picture_url, as: :file, input_html: { multiple: true }, placeholder: "Upload some pictures"  %>
      <%= f.input :sport_category, collection: ["kitesurf", "paddle", "planche à voile", "planche de surf", "vélo", "roller", "ski", "snowboard", "skateboard", "raquette de tennis"]  %>
      <%= f.submit "Add an offer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <h2 class="my-5 pt-5"><%= @offer.title.capitalize %> - <%=@offer.location %></h2>
    <div class="d-flex justify-content-around my-5">
          <% if @offer.picture_seed %>
            <% @offer.picture_seed.split(",").each do |picture| %>
              <img class="img-product" src=<%=picture%>  alt="img-product">
            <% end %>
          <% else %>
            <% @offer.picture_url.each do |offer| %>
              <%= cl_image_tag(offer.key, class: "img-product") %>
            <% end %>
          <% end %>
    </div>
  </div>
  <div class="container pb-5">
    <div class="d-flex justify-content-between">
      <div class="d-flex justify-content-between border-bottom border-primary pb-4" style="width: 700px">
          <div style="width: 600px" >
              <h2 class="border-bottom border-primary pb-4"><%=@offer.sport_category.capitalize%></h2>
              <h3 class="mt-4">Description</h3>
              <p><%=@offer.description%></p>
          </div>
          <div>
              <img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm">
          </div>
      </div>
      <div class ="form p-3">
          <h5 class="my-3 fw-bolder">Ajoutez des dates pour voir le prix</h5>
          <%= form_with url: new_offer_booking_path(@offer), method: :get, class: "" do %>
            <h6>Start date:</h6>
            <%= date_field_tag :start_date,
              params[:start_date] || Date.today,
              class: "form-control my-2"
            %>
            <h6>End date:</h6>
            <%= date_field_tag :end_date,
              params[:end_date] || Date.today,
              class: "form-control my-2"
            %>
            <%= submit_tag "Valider mes dates", class: "btn btn-primary form-btn mt-4" %>
          <% end %>
      </div>
    </div>
    <div class="" style="width: 700px">
      <div class="d-flex justify-content-start align-items-end mb-3">
          <h4 class="me-2"><i class="fa-solid fa-star mt-4"></i></h4>
          <% sum = 0 %>
          <%@offer.reviews.each do |review|%>
              <% sum += review.rating %>
            <% end %>
          <h4><%= (@offer.reviews.count == 0) ? "" : (sum.fdiv(@offer.reviews.count)).round(1) %> · </h4>
          <h4 class="ms-2"> <%= @offer.reviews.count%> commentaires</h4>
      </div>
          <% @offer.reviews.each do |review| %>
          <div class="d-flex justify-content-start">
            <% review.rating.times do %>
              <p><i class="fa-solid fa-star text-warning"></i></p>
            <% end %>
          </div>
            <p class="border-bottom pb-4"><%= review.content %></p>
          <% end %>
    </div>
     <div>
      <h3 class="mt-4 py-3">Où se situe le matériel</h3>
      <p><%= @offer.location %></p>
      <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>

app/views/pages/dashboard.html.erb
<br>
<br>
<div class="container mt-4">
  <h3 class="mt-5 border-bottom pb-3"> Pending booking requests</h3>
    <% current_user.offers.each do |offer| %>
      <% offer.bookings.each do |booking| %>
        <% if booking.status == "pending" %>
        <% then %>
          <div class="card-booking mt-3">
            <%= offer.picture_seed ? image_tag(offer.picture_seed.split(",").first) : cl_image_tag(offer.picture_url.first.key) %>
            <div class="card-booking-infos">
              <h2><%=booking.offer.title%></h2>
              <p>du <%=booking.start_date%> au <%=booking.end_date%></p>
            </div>
            <div class="btn-confirm">
              <h5><%= link_to "Accept", offer_booking_path(offer, booking, booking: { status: "confirmed" }), data:{turbo_method: :patch}, class:"text-decoration-none btn btn-primary btn-sm", id:"btn-reviews" %></h5>
            </div>
            <div class="btn-decline">
              <h5><%= link_to "Decline", offer_booking_path(offer, booking, booking: { status: "declined" }), data:{turbo_method: :patch}, class:"text-decoration-none btn btn-success btn-sm" %></h5>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>


  <div class="d-flex justify-content-between align-items-end  pb-3 border-bottom">
      <h3 class="mt-5"> My offers - (<%=@my_offers.count%>)</h3>
      <%= link_to "Create an offer", new_offer_path, class:"btn btn-primary"%>
  </div>
  <div class="card-container mt-5">
    <% @my_offers.each do |offer| %>
      <div class="card-scroll">
        <div class="card-offer effet mb-5">
          <%= offer.picture_seed ? image_tag(offer.picture_seed.split(",").first) : cl_image_tag(offer.picture_url.first.key) %>
          <div class="card-offer-infos">
            <h2><%= link_to offer.title, offer_path(offer)  %></h2>
            <h3><%= offer.location %></h3>
            <h4 class="card-offer-pricing"><%= offer.price %> € / day</h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container my-5">
  <h3 class="mt-5 pb-3 border-bottom">My bookings - (<%=@bookings.count%>) </h3>
  <div class="card-container mt-5">

      <% @bookings.each do |booking| %>
        <div class="card-scroll">
          <div class="card-offer effet">
            <%= booking.offer.picture_seed ? image_tag(booking.offer.picture_seed.split(",").first) : cl_image_tag(booking.offer.picture_url.first.key) %>
            <div class="card-offer-infos">
              <h2><%= booking.offer.title %></h2>
              <h3><%= booking.offer.location %></h3>
              <% length = (booking.end_date - booking.start_date).to_i %>
              <% total = length * booking.offer.price %>
                  <div><%= total %> €</div>
                   <% if booking.status == "pending" %>
              <% then %>
                <div class="btn-status btn-pending">
                  <h5>Pending confirmation</h5>
                </div>
              <% elsif booking.status == "confirmed" %>
                <div class="btn-status btn-confirmed">
                  <h5>Booking confirmed</h5>
                </div>
                <%= link_to "Give a review", new_booking_review_path(booking), class:"btn btn-sm btn-review", id: "btn-review"%>
              <% else %>
                <div class="btn-status btn-declined">
                  <h5>Booking declined</h5>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: url(https://cdn.pixabay.com/photo/2016/11/14/03/38/achieve-1822503_1280.jpg)">
  <div class=" card-home">
    <h2>Prêts à vivre une
    nouvelle experience ?</h2>
    <%= link_to "Parcourir nos offres", offers_path %>
  </div>
</div>

<div class="container p-5">
  <h2>Dernières offres </h2>
  <br>
  <div class="cards">
    <% @offers.each do |offer| %>
      <div class="card-offer">
          <%= offer.picture_seed ? image_tag(offer.picture_seed.split(",").first) : cl_image_tag(offer.picture_url.first.key) %>
        <div class="card-offer-infos">
          <div>
            <h2><%= link_to offer.title.capitalize, offer_path(offer)  %></h2>
            <h3><%= offer.location %></h3>
            <h4 class="card-offer-pricing"><%= offer.price %> € / day</h4>
            <i class="far fa-heart card-heart"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="form review">
    <h1>Make a review</h1>
    <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
      <%= f.input :content %>
      <%= f.submit "Add a review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Gear Sport
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon container-fluid">
  <%= link_to offers_path, class: "navbar-brand" do %>
    <%= image_tag "gear-sport-logo.png" %>
  <% end %>
  <%if current_user && params[:controller] == "offers" && params[:action] == "index"  %>
    <nav class="navbar">
      <div class="hello">
        <form class="d-flex me-5" role="search">
        <%= form_with url: offers_path, method: :get, class: "d-flex me-2 " do %>
          <%= text_field_tag :query, params[:query], class: "search-navbar", placeholder: "Votre recherche..." %>
          <button class="btn btn-outline-success ms-2" type="submit" style="border-radius: 30px">Search</button>
        <% end %>
        </form>
      </div>
    </nav>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/122464388?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Create an offer", new_offer_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item btn btn-outline-ligh">
          <%= link_to "S'inscrire | Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>